// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnCHikU5S0j5GhgP4U9KiuLMpwR3zT0ig',
    appId: '1:861108676025:web:a4b9199feafd0c7e4d8268',
    messagingSenderId: '861108676025',
    projectId: 'expence-tracker-7a85e',
    authDomain: 'expence-tracker-7a85e.firebaseapp.com',
    storageBucket: 'expence-tracker-7a85e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjdDgtble41RGuJ0WL3ntVkyTVCPGKNcA',
    appId: '1:861108676025:android:7547afaaf23eeb294d8268',
    messagingSenderId: '861108676025',
    projectId: 'expence-tracker-7a85e',
    storageBucket: 'expence-tracker-7a85e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1D0iSiDEjlNV-O0mGRHjKU8LF91Es02A',
    appId: '1:861108676025:ios:23e3c4d230cd5b5a4d8268',
    messagingSenderId: '861108676025',
    projectId: 'expence-tracker-7a85e',
    storageBucket: 'expence-tracker-7a85e.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1D0iSiDEjlNV-O0mGRHjKU8LF91Es02A',
    appId: '1:861108676025:ios:23e3c4d230cd5b5a4d8268',
    messagingSenderId: '861108676025',
    projectId: 'expence-tracker-7a85e',
    storageBucket: 'expence-tracker-7a85e.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnCHikU5S0j5GhgP4U9KiuLMpwR3zT0ig',
    appId: '1:861108676025:web:6caa20ec4ff7f5fd4d8268',
    messagingSenderId: '861108676025',
    projectId: 'expence-tracker-7a85e',
    authDomain: 'expence-tracker-7a85e.firebaseapp.com',
    storageBucket: 'expence-tracker-7a85e.firebasestorage.app',
  );
}
